Fix bundle for Juju 2.8 and test 2.8 in CI
juju-solutions/bundle-kubeflow pull request #225
Opened 2020-07-14 15:24 UTC by knkski

Fixes issue with mariadb charms not deploying properly with Juju 2.8, and adds Juju 2.8 to the CI testing

2020-07-14 18:43 UTC, cjohnston1158 commented
> LGTM, but don't forget to unpin that mariadb-k8s charm once 33 goes stable.

Should it not stay pinned so that we have a known working scenario rather than the ability for something to break if it changes?

2020-10-02 20:07 UTC, johnsca approved these changes
Seems fine to me, if everything's working as you expect.

2020-10-02 20:36 UTC, johnsca approved these changes

2020-10-21 14:29 UTC, johnsca requested changes

2020-10-21 14:29 UTC, johnsca commented on charms/dex-auth/reactive/dex_auth.py
> +    oidc_client_info = endpoint_from_name('oidc-client').get_config() or []
This has the potential to raise a "NoneType does not have attribute get_config" error if the relation doesn't exist.

```suggestion
    oidc_client = endpoint_from_name('oidc-client')
    oidc_client_info = oidc_client.get_config() if oidc_client else []
```

2020-10-21 14:45 UTC, johnsca approved these changes

2020-10-21 16:43 UTC, merged