Fix password handling in charms
juju-solutions/bundle-kubeflow pull request #246
Opened 2020-09-16 13:08 UTC by knkski

Removes the need for an overlay for specifying passwords that a user shouldn't need to concern themselves with.

2020-09-16 14:21 UTC, kwmonroe requested changes
Couple requests to set a different status, and I wanted to double check that you meant to lock those bundle revs in `./cli.py`.

2020-09-16 14:21 UTC, kwmonroe commented on charms/argo-controller/reactive/argo_controller.py
> +        layer.status.blocked('Waiting for minio relation.')
Suggest changing this to `.waiting` instead of `.blocked` -- you have `endpoint.minio.joined`, so there's nothing for an operator to do but wait.

2020-09-23 20:06 UTC, knkski commented on scripts/cli.py
> +        bundle_url = 'cs:~kubeflow-charmers/bundle/kubeflow-lite-12'
Got included before I was able to promulgate `kubeflow-lite` and `kubeflow-edge`. Switched these back since those are now promulgated.

2020-10-21 18:49 UTC, kwmonroe approved these changes

2020-10-21 20:15 UTC, merged